# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 435eb89e0bb1769071a1e46d1a1c1a3a70f8ef479c7c20c2a436b30f0c27f9215e2aadf2ace12909ee8a5103d3ee6bec2e94f9e93cedd3d54f3b0e7c4e4c3624

test:
  secret_key_base: f8ad9b7a904ce427d9ed4e2d057108e6003242d964cd5b86d1965d680dcae5244c25467f1279ce270fc4fe9de16f578086b41240ab99a165f7eac5886276b233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
